"""add todos relationship with user

Revision ID: 7b7f031af7af
Revises: 796573c30868
Create Date: 2026-03-06 08:21:28.882211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7f031af7af'
down_revision: Union[str, None] = '796573c30868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'author_id')
    # ### end Alembic commands ###
